name: group_manager_app
description: "A cross-platform mobile app for group management"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.4
  cloud_firestore: ^5.2.1
  firebase_storage: ^12.3.2
  
  # State Management
  provider: ^6.1.1
  
  # Utilities
  intl: ^0.18.1
  uuid: ^4.3.3
  
  # File & Storage
  file_picker: ^8.0.0
  path_provider: ^2.1.4
  shared_preferences: ^2.2.2
  http: ^1.1.0
  
  # Audio
  just_audio: ^0.9.40
  
  # UI
  cupertino_icons: ^1.0.2
  qr_flutter: ^4.1.0
  mobile_scanner: ^5.2.3
  google_mobile_ads: ^5.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "ic_launcher"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21

flutter:
  uses-material-design: true
